# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "mvanbeusekom"
    labels:
      - "platform: ci"

  - package-ecosystem: "gradle"
    directory: "/geolocator_android/android"
    commit-message:
      prefix: "[geolocator_android]"
    schedule:
      interval: "weekly"
    reviewers:
      - "mvanbeusekom"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "com.google.android.gms:play-services-location"
        update-types: ["version-update:semver-major", "version-update:semver-minor", "version-update:semver-patch"]
      - dependency-name: "com.android.tools.build:gradle"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
      - dependency-name: "junit:junit"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
      - dependency-name: "org.mockito:*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
      - dependency-name: "androidx.test:*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]

  - package-ecosystem: "gradle"
    directory: "/geolocator_android/example/android/app"
    commit-message:
      prefix: "[geolocator_android]"
    schedule:
      interval: "weekly"
    reviewers:
      - "mvanbeusekom"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]

  - package-ecosystem: "gradle"
    directory: "/geolocator/example/android/app"
    commit-message:
      prefix: "[geolocator]"
    schedule:
      interval: "weekly"
    reviewers:
      - "mvanbeusekom"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]

  - package-ecosystem: "pub"
    directory: "/geolocator"
    commit-message:
      prefix: "[geolocator]"
    schedule:
      interval: "weekly"
    reviewers:
      - "mvanbeusekom"
    open-pull-requests-limit: 10
    
  - package-ecosystem: "pub"
    directory: "/geolocator/example"
    commit-message:
      prefix: "[geolocator]"
    schedule:
      interval: "weekly"
    reviewers:
      - "mvanbeusekom"
    open-pull-requests-limit: 10

  - package-ecosystem: "pub"
    directory: "/geolocator_android"
    commit-message:
      prefix: "[geolocator_android]"
    schedule:
      interval: "weekly"
    reviewers:
      - "mvanbeusekom"
    open-pull-requests-limit: 10
    
  - package-ecosystem: "pub"
    directory: "/geolocator_android/example"
    commit-message:
      prefix: "[geolocator_android]"
    schedule:
      interval: "weekly"
    reviewers:
      - "mvanbeusekom"
    open-pull-requests-limit: 10

  - package-ecosystem: "pub"
    directory: "/geolocator_apple"
    commit-message:
      prefix: "[geolocator_apple]"
    schedule:
      interval: "weekly"
    reviewers:
      - "mvanbeusekom"
    open-pull-requests-limit: 10
    
  - package-ecosystem: "pub"
    directory: "/geolocator_apple/example"
    commit-message:
      prefix: "[geolocator_apple]"
    schedule:
      interval: "weekly"
    reviewers:
      - "mvanbeusekom"
    open-pull-requests-limit: 10

  - package-ecosystem: "pub"
    directory: "/geolocator_linux"
    commit-message:
      prefix: "[geolocator_linux]"
    schedule:
      interval: "weekly"
    reviewers:
      - "mvanbeusekom"
    open-pull-requests-limit: 10
    
  - package-ecosystem: "pub"
    directory: "/geolocator_linux/example"
    commit-message:
      prefix: "[geolocator_linux]"
    schedule:
      interval: "weekly"
    reviewers:
      - "mvanbeusekom"
    open-pull-requests-limit: 10

  - package-ecosystem: "pub"
    directory: "/geolocator_platform_interface"
    commit-message:
      prefix: "[geolocator_platform_interface]"
    schedule:
      interval: "weekly"
    reviewers:
      - "mvanbeusekom"
    open-pull-requests-limit: 10

  - package-ecosystem: "pub"
    directory: "/geolocator_web"
    commit-message:
      prefix: "[geolocator_web]"
    schedule:
      interval: "weekly"
    reviewers:
      - "mvanbeusekom"
    open-pull-requests-limit: 10
    
  - package-ecosystem: "pub"
    directory: "/geolocator_web/example"
    commit-message:
      prefix: "[geolocator_web]"
    schedule:
      interval: "weekly"
    reviewers:
      - "mvanbeusekom"
    open-pull-requests-limit: 10

  - package-ecosystem: "pub"
    directory: "/geolocator_windows"
    commit-message:
      prefix: "[geolocator_windows]"
    schedule:
      interval: "weekly"
    reviewers:
      - "mvanbeusekom"
    open-pull-requests-limit: 10
    
  - package-ecosystem: "pub"
    directory: "/geolocator_windows/example"
    commit-message:
      prefix: "[geolocator_windows]"
    schedule:
      interval: "weekly"
    reviewers:
      - "mvanbeusekom"
    open-pull-requests-limit: 10
