name: Submit a regression
description: Report unexpected behavior that worked in a previous version of the plugin.
title: "[Regression]: "
labels: ["needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to submit a regression!
        To effectively tackle it, we require as much information as possible. This might seem a lot of information but 
        will allow us to quickly get to the root of the regression.
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for this feature request or proposal.
      options:
        - label: I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
          required: true
  - type: checkboxes
    attributes:
      label: Please select affected platforms
      options:
      - label: Android
      - label: iOS
      - label: Linux
      - label: macOS
      - label: Web
      - label: Windows
  - type: textarea
    attributes:
      label: Old (and correct) behavior
      description: |
        Briefly but precisely describe what the geolocator plugin was able to do before the regression occurred.

        Consider attaching something showing the old behavior:
         * code samples
         * images
         * videos
    validations:
      required: true
  - type: textarea
    attributes:
      label: Current behavior
      description: |
        Briefly but precisely describe what the geolocator plugin is doing now.

        Consider attaching something showing the current behavior:
         * code samples
         * images
         * videos
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Please provide specific steps to reproduce the situation in which the regression manifests.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Code sample
      description: |
        Please create a minimal reproducible sample that shows the problem
        and attach it below between the lines with the backticks.
        
        Note: Please do not upload screenshots of text. Instead, use code blocks
        or the above mentioned ways to upload your code sample.
      value: |
        <details><summary>Code sample</summary>

        ```dart
        [Paste your code here]
        ```

        </details>
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots or Video
      description: |
        Upload any screenshots or video of the regression if applicable.
      value: |
        <details>
        <summary>Screenshots / Video demonstration</summary>

        [Upload media here]

        </details>
  - type: input
    attributes:
      label: Current version
      description: Which version of the plugin are you currently using?
      placeholder: ex. 1.2.3
    validations:
      required: true
  - type: input
    attributes:
      label: Last version without regression
      description: In which version of the geolocator plugin was the regression not yet present?
      placeholder: ex. 1.2.2
    validations:
      required: true
