name: Report a bug
description: You encountered an issue in your application using the geolocator plugin.
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to file an issue for this plugin!
        To tackle this issue effectively, we require as many details as possible.
        
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      options:
        required: true
  - type: checkboxes
    attributes:
      label: Which platforms are affected?
      options:
      - label: Android
      - label: iOS
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Please tell us exactly how to reproduce the issue you encounter.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected results
      description: Please tell us what is expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual results
      description: Please tell us what is actually happening.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Code sample
      description: |
        Please create a minimal reproducible sample that shows the problem
        and attach it below between the lines with the backticks.

        To create it, use the `flutter create bug` command and update the `main.dart` file.

        Alternatively, you can use https://dartpad.dev/ or create a public GitHub
        repository to share your sample.

        Having a code sample will dramatically increase our ability to locate and fix the issue.
      value: |
        <details><summary>Code sample</summary>

        ```dart
        [Paste your code here]
        ```

        </details>
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots or Video
      description: |
        Upload any screenshots or video showcasing the issue if applicable.
      value: |
        <details>
        <summary>Screenshots / Video demonstration</summary>

        [Upload media here]

        </details>
  - type: textarea
    attributes:
      label: Flutter Doctor output
      description: |
        Please provide the full output of running `flutter doctor -v`
      value: |
        <details><summary>Doctor output</summary>

        ```console
        [Paste your output here]
        ```

        </details>
    validations:
      required: true
