name: Report a bug
description: You encountered a bug in the geolocator plugin resulting in application crashes, compilation errors or invalid/ unexpected results.
title: "Bug: "
labels: ["needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to submit an issue!
        To effectively tackle it, we require as much information as possible. This might seem a lot of information but 
        will allow us to quickly help you and resolve the issue you are facing.
  - type: checkboxes
    attributes:
      options:
      - label: I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues)
        required: true
  - type: checkboxes
    attributes:
      label: Please select affected platforms
      options:
      - label: Android
      - label: iOS
      - label: Linux
      - label: macOS
      - label: Web
      - label: Windows
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Please tell us exactly how to reproduce the problem you are running into.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected results
      description: Please tell us what is expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual results
      description: Please tell us what is actually happening.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Code sample
      description: |
        Please create a minimal reproducible sample that shows the problem
        and attach it below between the lines with the backticks.
        
        Note: Please do not upload screenshots of text. Instead, use code blocks
        or the above mentioned ways to upload your code sample.
      value: |
        <details><summary>Code sample</summary>

        ```dart
        [Paste your code here]
        ```

        </details>
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots or Video
      description: |
        Upload any screenshots or video of the bug if applicable.
      value: |
        <details>
        <summary>Screenshots / Video demonstration</summary>

        [Upload media here]

        </details>
  - type: textarea
    attributes:
      label: Flutter Doctor output
      description: |
        Please provide the full output of running `flutter doctor -v`
      value: |
        <details><summary>Doctor output</summary>

        ```console
        [Paste your output here]
        ```

        </details>
    validations:
      required: true
