name: Submit an enhancement proposal
description: Do you have a proposal for code cleanup, a refactor, or other improvements? Submit them here!
title: "[Enhancement proposal]: "
labels: ["needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to submit an enhancement proposal!
        Please take the time to fill out the information below so that we can better evaluate the need for the enhancement.
  - type: checkboxes
    attributes:
      label: Please check the following before submitting a new issue.
      options:
        - label: I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
          required: true
        - label: I have carefully [read the documentation](https://github.com/baseflow/flutter-geolocator/blob/main/geolocator/README.md) and verified I have added the required platform specific configuration.
          required: true
  - type: checkboxes
    attributes:
      label: Please select affected platforms
      options:
      - label: Android
      - label: iOS
      - label: Linux
      - label: macOS
      - label: Web
      - label: Windows
  - type: textarea
    attributes:
      label: Proposal
      description: |
        Please provide a clear and concise description of your idea.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Pitch
      description: |
        How will this refactor improve contributors' lives? Input as many details as possible!
    validations:
      required: true
