include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    # Ignore generated files
    - '**/*.g.dart'
    - 'lib/src/generated/*.dart'
    - build/**
    - android/**
linter:
  rules:
    - public_member_api_docs