name: geolocator_linux

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
    paths:
    - 'geolocator_linux/**'
    - '.github/workflows/geolocator_linux.yaml'
  pull_request:
    branches: [ main ]
    paths:
    - 'geolocator_linux/**'
    - '.github/workflows/geolocator_linux.yaml'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ci:
    name: Linux platform package

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      source-directory: ./geolocator_linux
      example-directory: ./geolocator_linux/example 

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      # Make sure the stable version of Flutter is available
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: |
              sudo apt-get update -y
              sudo apt-get install -y ninja-build libgtk-3-dev
      # Enable Flutter Linux Desktop support (not on by default in stable yet)
      - name: Enable Flutter Linux Desktop support
        run: flutter config --enable-linux-desktop
        working-directory: ${{env.source-directory}}

      # Download all Flutter packages
      - name: Download dependencies
        run: flutter pub get
        working-directory: ${{env.source-directory}}

      # Run Flutter Format to ensure formatting is valid
      - name: Run Flutter Format
        run: dart format --set-exit-if-changed .
        working-directory: ${{env.source-directory}}

      # Run Flutter Analyzer
      - name: Run Flutter Analyzer
        run: flutter analyze
        working-directory: ${{env.source-directory}}

      # Build Linux version of the example App
      - name: Run Linux build
        run: flutter build linux --release
        working-directory: ${{env.example-directory}}

      # Run all unit-tests with code coverage
      - name: Run unit tests
        run: flutter test --coverage
        working-directory: ${{env.source-directory}}
